[mongodb]
mongodb-dev.jai01.online

[catalouge]
catalogue-dev.jai01.online

[redis]
redis-dev.jai01.online

[user]
user-dev.jai01.online

[cart]
cart-dev.jai01.online

[mysql]
mysql-dev.jai01.online

[shipping]
shipping-dev.jai01.online

[rabbitmq]
rabbitmq-dev.jai01.online

[Payment]
Payment-dev.jai01.online

[frontend]
frontend-dev.jai01.online

[all:vars]
ansible_users=ec2-user
ansible_password=DevOps321
Mongodb_Host=mongodb-dev.jai01.online
Catalogue_Host=catalogue-dev.jai01.online
Redis_Host=redis-dev.jai01.online
User_Host=user-dev.jai01.online
Cart_Host=cart-dev.jai01.online
Mysql_Host=mysql-dev.jai01.online
Shipping_Host=shipping-dev.jai01.online
Payment_Host=Payment-dev.jai01.online
 