- name: configure the payment server
  become: yes
  hosts: payment

  tasks:
    - name: install paython
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
      - python3 
      - gcc python3-devel

    - name: create the system user
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"
    
    - name: delete old directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: delete zip file
      ansible.builtin.file:
        path: /tmp/payment.zip
        state: absent

    - name: download the payment application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        path: /app
        dest: /tmp/payment.zip
    
    - name: unizp the application
      ansible.builtin.unarchieve:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes
    
    - name: install the dependencies
      ansible.builtin.pip:
        requirements: requirements.txt
        executable: pip3.13 
    
    - name: copy payment service
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service
    
    - name: daemon reload
      ansible.builtin.service:
        daemon_reload: yes
    
    - name: start and reload payment
      ansible.builtin.service:
        name: payment
        start: restarted
        enable: yes

