- name: configure rabbitmq
  become: yes
  hosts: rabbitmq

  tasks:

    - name: copy rabbitmq repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: install rabbitmq
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: present

    - name: start and enable rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: add rabbitmq user
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123
      ignore_errors: yes
      overwrite: yes

    - name: set permissions
      ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"