- name: configure the shipping server
  become: yes
  hosts: shipping

  tasks:

    - name: install maven
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: add system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        comment: "roboshop system user"

    - name: delete any old app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: unzip application
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: install dependencies (maven build)
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: copy shipping service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: start shipping service
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: yes
    
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql
        state: present
    
    - name: load the schema in database
      community.mysql.mysql_db:
        state: import
        name: mysql
        target: /app/db/schema.sql
      loop:
        /app/db/schema.sql
        /app/db/app-user.sql
        /app/db/master-data.sql 
    
    - name: start the service
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes