- name: configure user
  become: yes
  host: user

  tasks:
    - name: check the nodejs version available
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable the nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.command: dnf install nodejs